Add patch-hack.sh script
source-foundry/alt-hack pull request #40
Opened 2018-08-29 19:22 UTC by vl4dimir

Adds a simple script which automates the tedious manual copying of individual `.glif` files into the Hack repo.

2018-09-03 23:02 UTC, chrissimpkins requested changes
Thanks for submitting this script Vlad!  This will be fantastic!!  Mind having a look at these `shellcheck` suggestions and making modifications to make shellcheck tests pass on the new script file?

2018-09-03 23:02 UTC, chrissimpkins commented on patch-hack.sh
> +        lowercaseStyle=`echo "$style" | tr '[:upper:]' '[:lower:]'`
from shellcheck: 

```
In patch-hack.sh line 38:
        lowercaseStyle=`echo "$style" | tr '[:upper:]' '[:lower:]'`
                       ^-- SC2006: Use $(..) instead of legacy `..`.
```

2018-09-03 23:02 UTC, chrissimpkins commented on patch-hack.sh
> +        cp $alternatePath $stylePath
from shellcheck:

```
In patch-hack.sh line 41:
        cp $alternatePath $stylePath
           ^-- SC2086: Double quote to prevent globbing and word splitting.
                          ^-- SC2086: Double quote to prevent globbing and word splitting.
```

2018-09-03 23:02 UTC, chrissimpkins commented on patch-hack.sh
> +        if [ $? -ne 0 ]; then
from shellcheck: 

```
In patch-hack.sh line 42:
        if [ $? -ne 0 ]; then
             ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
```

I use the idiom that you used above too.  Thoughts about modifying as suggested here?

2018-09-04 13:34 UTC, vl4dimir commented
@chrissimpkins Sure thing, here's an updated version. I didn't know about `shellcheck`, I needed that tool for so long. 😆

2018-09-05 03:43 UTC, merged

2018-09-05 03:44 UTC, chrissimpkins reviewed
@vl4dimir looks great!  Merging and will add CI testing for the shell script.

2018-09-05 04:05 UTC, chrissimpkins commented
@vl4dimir added CI testing!